#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_EDIT_TABS                           101
#define IDM_ABOUT                               104
#define IDI_DESKTOP                             107
#define IDI_SMALL                               108
#define IDD_ADD_FIELD                           110
#define IDI_NEW                                 110
#define IDC_NEW_FIELD_NAME                      111
#define IDC_NEW_FIELD_TYPE                      112
#define IDD_EDIT_FIELDS                         114
#define IDD_EDIT_COLUMNS                        116
#define IDD_ADD_TAB                             118
#define IDD_ADD_VIEW                            159
#define IDD_ADD_DOCUMENT_TYPE                   298
#define IDD_ADD_EXISTING_VIEW                   301
#define IDC_ADD_FIELD_CHOOSE_FROM_LABEL         1000
#define IDC_PICK_VIEW_COMBO                     1001
#define IDC_RELATIONSHIP_COMBO                  1001
#define IDC_RELATIONSHIP_LABEL                  1002
#define IDC_STATIC1                             1002
#define IDC_CONDITIONS_LABEL                    1003
#define IDC_ADD_DOCUMENT_TYPE_NAME              1004
#define IDC_ADD_DOCUMENT_TYPE_LABEL             1005
#define IDC_ADD_VIEW_DOC_TYPE                   1006
#define IDC_HIDDEN_FIELDS                       1007
#define IDC_ADD_DOCUMENT_FIRST_FIELD_NAME       1008
#define IDC_HIDDEN_TABS                         1008
#define IDC_ADD_DOCUMENT_FIRST_FIELD_LABEL      1009
#define IDC_VISIBLE_TABS                        1009
#define IDC_ADD_DOCUMENT_TYPE_PLURAL_LABEL      1012
#define IDC_ADD_TO_VISIBLE_TABS                 1013
#define IDC_FIELD_TYPE_COMBO                    1014
#define IDC_REMOVE_FROM_VISIBLE_TABS            1014
#define IDC_NEW_VIEW_SORT_BY                    1019
#define IDC_NEW_VIEW_NAME                       1020
#define IDB_TREE                                9482
#define IDC_DESKTOP                             40000
#define IDC_VISIBLE_UP                          40002
#define IDC_VISIBLE_DOWN                        40003
#define IDC_VISIBLE_FIELDS                      40003
#define IDC_ADD_TO_VISIBLE_FIELDS               40004
#define IDC_REMOVE_FROM_VISIBLE_FIELDS          40005
#define IDC_NEW_FIELD                           40007
#define IDC_FIELD_UP                            40008
#define IDC_FIELD_DOWN                          40009
#define IDC_NEW_FIELD_LABEL                     40010
#define IDC_ADD_FIELD_VIEW_TREE                 40011
#define IDC_NEW_FIELD_OPTIONS                   40013
#define IDC_NEW_FIELD_NEW_OPTION                40014
#define IDC_NEW_FIELD_ADD_OPTION                40016
#define IDC_NEW_TAB                             40017
#define IDC_CONTENT_COMBO                       40021
#define IDC_NEW_TAB_LABEL                       40022
#define IDC_NEW_TAB_NAME                        40023
#define IDR_SMALL_ADD_BITMAP                    40024
#define IDB_FOLDER                              40025
